version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: temporal-postgres
    environment:
      - POSTGRES_USER=temporal
      - POSTGRES_PASSWORD=temporal
      - POSTGRES_DB=temporal
    ports:
      - "0.0.0.0:5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U temporal -d temporal"]
      interval: 5s
      timeout: 5s
      retries: 10

  temporal:
    image: temporalio/auto-setup:latest
    container_name: temporal
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DB=postgres12
      - DB_PORT=5432
      - POSTGRES_SEEDS=postgres
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_DB=temporal
    ports:
      - "0.0.0.0:7233:7233"

  temporal-ui:
    image: temporalio/ui:latest
    container_name: temporal-ui
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
    ports:
      - "0.0.0.0:8081:8080"
    depends_on:
      - temporal

  worker:
    build: ./TemporalWorker
    container_name: temporal-worker
    environment:
      - TEMPORAL__ADDRESS=temporal:7233
      - TASK_QUEUE=housing-loans
    depends_on:
      - temporal

  webapi:
    build: ./TemporalWebApi
    container_name: temporal-webapi
    ports:
      - "5044:5044"
    environment:
      - TEMPORAL__ADDRESS=temporal:7233
    depends_on:
      - temporal
